title: GameDepot API
color_scheme: gamedepot
aux_links:
  "Quick Start": "/"
  "Games Resource": "/api/games"
  "Get All Games": "/api/games-get-all-games"
  "Get Game by ID": "/api/games-get-game-by-id"