title: GameDepot API
remote_theme: just-the-docs/just-the-docs
color_scheme: gamedepot
baseurl: /gamedepot

aux_links:
  "Quick Start": "https://maudeekauffman.github.io/gamedepot/"
  "Games Resource": "https://maudeekauffman.github.io/gamedepot/api/games"
  "Get All Games": "https://maudeekauffman.github.io/gamedepot/api/games-get-all-games"
  "Get Game by ID": "https://maudeekauffman.github.io/gamedepot/api/games-get-game-by-id"